### ISSUE TITLE
samba无法连接

### ISSUE THREAD

**Issue by sazima** [hanxi/media-server-docker-compose#2]
![smb.png](https://i.loli.net/2019/11/13/ptIPhnzE6Nui2mw.png)

```bash
docker-compose up -d 
```
后不能远程进入目录, 用户名和密码都是samba没有修改.
请问是不是需要其他的设置

**Comment by hanxi** [comment]
我也不知道咋解决这个问题，你试试在手机上下个smb客户端连接试试？我猜是 windows 10 兼容性的问题。

**Comment by hanxi** [comment]
@sazima  试试这个方法 https://www.jianshu.com/p/8135a8eb095c

**Comment by sazima** [comment]
谢谢, 我换台机器试下.

**Comment by sazima** [comment]
手机可以连接, 是win10客户端的问题,
